### ISSUE TITLE
layout - color scheme

### ISSUE THREAD

**Issue by auxibackup** [chingu-voyages/v9-geckos-team-08#6]
Need set of primary colors for layout

**Comment by Javiercerna** [comment]
What about these options?

**Option 1**

![image](https://user-images.githubusercontent.com/7322431/59651148-5f11f600-914e-11e9-9445-67884faf213c.png)

**Option 2**

![image](https://user-images.githubusercontent.com/7322431/59651199-984a6600-914e-11e9-96d7-e6d9d9ca781e.png)

**Option 3**

![image](https://user-images.githubusercontent.com/7322431/59651220-ae582680-914e-11e9-9551-3ef7a6baa5af.png)

**Option 4**

![image](https://user-images.githubusercontent.com/7322431/59652079-dc8b3580-9151-11e9-8b6f-0434dbfc97c7.png)

**Comment by auxibackup** [comment]
3 looks easier on the eyes. Whose knows, might change as project progress

**Comment by Javiercerna** [comment]
All right! This is the color scheme for option 3:

![image](https://i.ibb.co/j4CNSJH/color-scheme.png)
